homeassistant:
# Name of the location where Home Assistant is running
# Location required to calculate the time the sun rises and sets
# Impacts weather/sunrise data (altitude above sea level in meters)
# metric for Metric, imperial for Imperial
# Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  name: Condo
  latitude: !secret config_latitude
  longitude: !secret config_longitude
  elevation: 377
  unit_system: imperial
  external_url: https://beed2112az.duckdns.org/
  internal_url: https://beed2112az.duckdns.org/
#  whitelist_external_dirs:
#    - www 
  
  time_zone: America/Phoenix

  #customize: !include customize.yaml  

# a directory of automaions
  #customize: !include_dir_merge_named customize/

  customize: !include customize.yaml

  packages: !include_dir_named packages



# new auth section

  auth_providers:
   - type: legacy_api_password
     api_password: !secret api_pass

 # system_health:
# 
#default_config:
#
#influx "telemetry database - using different host"
#influxdb:
#  host: !secret influx_host
#  database: !secret influx_db
#  default_measurement: state
  
#panel_custom:
#  - name: zwavegraph2
#    sidebar_title: ZWave Graph2
 #   sidebar_icon: mdi:access-point-network
 #   url_path: zwave

cloud: 
  alexa:
    filter:
      include_domains:
        - switch
        - light
#        - group
        - input_boolean
        - climate
     # include_entities:
      #  - zwave.mudroom_receptacle
      #  - zwave.lrwarmer
       # - zwave.entryhalltable
      # - zwave.vanity_left
      #  - zwave.vanity_right
       # - zwave.lr_light  
        

#zwave:
 # usb_path: /dev/ttyACM0
 # network_key: !secret zwavekey
  


# mqtt using remote host
mqtt:
  broker: !secret mqttserver
  client_id: haserver2
#  username: !secret mqtt_user
#  password: !secret mqtt_pass
  discovery: true
  discovery_prefix: homeassistant
  
########################################################automation stuff
    
# a directory of automaions
automation: !include_dir_merge_list automations/


# for testing to specific a specific file only
#automation: !include automations/alarm.yaml

 

#iOS notification
notify:
  - name: iOSApp
    platform: ios
    # target: !secret iosapp_target
    target:
      - target: !secret iosapp_target
      - target: !secret iosapp_target_melodie
      - target: !secret iosapp_target_mikepad
  - name: syslog
    platform: syslog
#  - platform: alexa_media
#    name: alexa_media  
    #platform: alexa_media
       


# Enables configuration UI
config:


http:

  

 # api_password: !secret api_pass
  #ssl_certificate: !secret ssl_certificate
 # ssl_key: !secret ssl_key
  # base_url: !secret base_url
  # ip_ban_enabled: True
  # login_attempts_threshold: 5

# Checks for available updates
#updater:
 # include_used_components: true

#Discover some devices automatically
#discovery:
  #ignore:
   # - apple_tv
   # - samsung_tv
 
ssdp:
zeroconf:
ios:  


# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:


#lifx:
 # light:

python_script:


 #not using
#media_player:
#  - platform: firetv
#     host: !secret lr-firetv
#     device: lr-firetv



alexa_media:
  accounts:
    - email: !secret amazonId
      password: !secret amazonPass
      url: amazon.com


wemo: !include wemo.yaml

#wemo:

#ios: !include ios.yaml

  


shell_command: !include shell_command.yaml


    

# tracked:
# Show links to resources in log and frontend
#introduction:

# Enables the frontend

#frontend: !include frontend.yaml

  


recorder: !include recorder.yaml

# Enables support for tracking state changes over time.
#history: !include history.yaml

# View all events in a logbook
logbook: !include logbook.yaml

# what we log to HAs log and syslog
logger: !include logger.yaml

    
# Track the sun
sun:
  

  
 

# Weather Prediction
 - platform: yr
   monitored_conditions:
    - WindSpeed


# Text to speech
# tts:
#   platform: google

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

mobile_app:

device_tracker:
  - platform: ddwrt
    host: !secret ddwrt_host
    username: !secret ddwrt_username
    password: !secret ddwrt_password
  - platform: bluetooth_tracker
    new_device_defaults:
      track_new_devices: True

#sense:
#  email: !secret senseID
#  password: !secret sensePassword
#  timeout: 30

light: !include light.yaml

 

sensor: !include sensor.yaml



switch: !include switch.yaml


group: !include groups.yaml



script: !include scripts.yaml



input_number: !include input_number.yaml


input_boolean: !include input_boolean.yaml

input_select: !include input_select.yaml


notify ios:
  - name: iOS
    platform: group
    services:
      - service: ios_michaels_iphone
      - service: ios_iphone_melodie_personal
      - service: ios_mike_ipad
notify syslog:
  - name: syslogit
    platform: group
    services:
      - service: syslog
    


#alert: !include alert.yaml



binary_sensor: !include binary_sensor.yaml

####----my example for when i figure out what i really want here.
# panel_iframe:
#   grafana:
#     title: Dashboard
#     icon: mdi:vector-square
#     url: http://


#define the timer - duration specified in seconds
timer: !include timer.yaml
  

    
counter:
  shade_raised_counter:
    initial: 0
    step: 1
  wind_reset_counter:
    initial: 0
    step: 1    

input_datetime:
  vacation_return_date:
    name: Vacation Return Date
    has_date: true
    has_time: false

    

scene:
  - name: shade_up
    entities:
      switch.somfy: false
 
  - name: shade_down
    entities:
      switch.somfy: true   
 
  - name: night_time
    entities:
      input_boolean.night_mode: true       
 
  - name: day_time
    entities:
      input_boolean.night_mode: false     
 
  - name: leaving_home
    entities:
      script.empty_condo: on       
 
  - name: white_light
    entities:
      script.white: on                  
 
  - name: green_light
    entities:
      script.green: on 













