#-autodoc
#-autodoc        name: Morning Alarm
#-autodoc description: If alarm status is on trigger when current time equal alarm set time.  Will turn on the devices in group.morning and send notify to phone.
#-autodoc        file: alarm.yaml
#-autodoc

# Alarm Clock
- alias: 'Morning alarm'
  initial_state: True
  trigger:
    platform: template
    value_template: '{{ states.sensor.time.state == states.sensor.alarm_clock_time_long.state }}'
  condition:
    condition: state
    entity_id: input_boolean.alarm_clock_status
    state: 'on'
  action:
    - service: switch.turn_on
      entity_id: group.morning
    - service: media_player.play_media
      data:
        entity_id: media_player.den
        media_content_type: sound
        media_content_id: 'amzn_sfx_rooster_crow_01'    
    - delay: 00:02:00
    - service: notify.ios_michaels_iphone
      data:
        message: "Good Morning!"
        data:
          push:
             sound: "US-EN-Alexa-Good-Morning.wav"
            # badge: 5
  
