- alias: 'Motion for Kitchen light on'
  initial_state: False
  trigger:
    - platform: state
      entity_id: sensor.multikitchen_burglar
      from: '0'
      to: '8'
#  condition:
#    condition: state
#    entity_id: light.kitchenundercab
#    state: 'off'
  condition:
#    - condition: state
#      entity_id: input_boolean.night_mode
#      state: 'off'  
    - condition: state
      entity_id: light.kitchenundercab
      state: 'off'
    - condition: state
      entity_id: light.kitchenoh
      state: 'off'    
    - condition: state
      entity_id:  light.diningroom
      state: 'off'
  action:
    - service: light.turn_on
      entity_id:
        - light.kitchenundercab
    - service: timer.start
      data_template:
        entity_id: "timer.kitchen_motion"
        duration: '{{ states.input_number.kitchen_motion_time_on.state | multiply(60) |int}}'
    - service: homeassistant.turn_on
      entity_id: input_boolean.motionactivated_kitchen

#Restart the timer when motion detected.  On time is set in the GUI

- alias: 'Motion for kitchen light timer restart'
  initial_state: True
  trigger:
    - platform: state
      entity_id: sensor.multikitchen_burglar
      from: '0'
      to: '8'
  condition:
    condition: state
    entity_id: input_boolean.motionactivated_kitchen
    state: 'on'
  action:
    - service: timer.start
      data_template:
        entity_id: "timer.kitchen_motion"
        duration: '{{ states.input_number.kitchen_motion_time_on.state | multiply(60) |int}}'

#-If timer ends motion has not been detected turn light off. On time is set in the GUI

- alias: 'Motion kitchen light time ends'
  initial_state: True
  trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.kitchen_motion
  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.motionactivated_kitchen
    - service: light.turn_off
      entity_id:
        - light.kitchenundercab