# Turn on stuff in sunset group at (sunset - 30min )

- alias: 'LR switch Sunset on'
  initial_state: True
  trigger:
    platform: sun
    event: sunset
    offset: '-01:00:00'
  action:
    - service: switch.turn_on
      entity_id:
      - switch.lr_switch
      - switch.lrlight_switch


- alias: 'LR switch Sunset(+3) off'
  initial_state: False
  trigger:
    platform: sun
    event: sunset
    offset: '+03:00:00'
  action:
    - service: switch.turn_off
      entity_id:
      - switch.lr_switch
      - switch.lrlight_switch


- alias: 'Patio CF Light on'
  initial_state: False
  trigger:
    platform: time
    at: '22:59:00'
  action:
   - service: switch.turn_on
     entity_id:
     - switch.patiolight

- alias: 'Den Dresser Sunset on'
  initial_state: True
  trigger:
    platform: sun
    event: sunset
    #offset: '-01:00:00'
  action:
    - service: switch.turn_on
      entity_id:
      - switch.dendresser

- alias: 'Entry Table Sunset on'
  initial_state: True
  trigger:
    platform: sun
    event: sunset
    #offset: '-01:00:00'
  action:
    - service: switch.turn_on
      entity_id:
      - switch.entryhalltable_switch      
