# Turn on Patio outlet

- alias: 'Patio outlet on at Sunset'
  initial_state: True
  trigger:
    platform: sun
    event: sunset
  action:
    - service: switch.turn_on
      entity_id:
      - switch.patiooutlet
      
#At xmas turn off patio outlet and turn on ceiling fan light - enabled during xmas season

- alias: 'Xmas off Patio CF Light on'
  initial_state: True
  trigger:
    platform: time
    at: '23:00:00'
  action:
   - service: switch.turn_off
     entity_id:
     - switch.patiooutlet
   #- service: switch.turn_on
    # entity_id:
   #  - switch.patiolight

