################################################################
## Packages / Cameras
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'cameras.yaml'
   
    sensor.camera_den_bitrate:
      friendly_name: 'DenCam link bitrate'
      icon: mdi:rocket   
    sensor.camera_den_link_quality:
      friendly_name: 'DenCam link qaulity'
      icon: mdi:thumb-up-outline    
    sensor.camera_den_load:  
      friendly_name: 'DenCam CPU load'
      icon: mdi:run
    sensor.camera_den_noise_level:   
      friendly_name: 'DenCam link noise'
      icon: mdi:thumb-down-outline
    sensor.camera_den_signal_level:
      friendly_name: 'DenCam Signal'
      icon: mdi:signal-cellular-outline
    sensor.camera_den_ssid:
      friendly_name: 'DenCam link'
      icon: mdi:access-point-network
    sensor.camera_den_uptime:
      friendly_name: 'DenCam uptime'
      icon: mdi:clock
    sensor.camera_den_users:
      friendly_name: 'DenCam users'
      icon: mdi:human-male-female
    counter.motion_pics_den:
      friendly_name: 'DenCam captures'
      icon: mdi:sort-numeric
    binary_sensor.cameraden_motion_sensor:
      friendly_name: 'DenCam motion'
  
counter:
  motion_pics_den:
    initial: 0
    step: 1


automation:

- alias: 'Den save motion snapshot'
  initial_state: True
  trigger:
    platform: mqtt
    topic: myhome/cameraden/motion  
    # Optional
#    payload: 'on'
    encoding: ''
  action:
    - service: camera.snapshot
      data:
        entity_id: camera.cameraden_motion_snapshot
        filename: '/config/www/Photos/den_{{ now().strftime("%Y%m%d-%H%M%S") }}.jpg'
    - service: counter.increment 
      entity_id: counter.motion_pics_den     


- alias: 'reset motion capture counter'
  initial_state: True
  trigger:
    platform: time
    at: '23:59:59'
  action:
    - service: counter.reset
      entity_id: counter.motion_pics_den  


- alias: 'master cam snapshot'
  initial_state: False
  trigger:
    platform: time
    at: '08:15:00'
  action:
    - service: homeassistant.update_entity
      entity_id: binary_sensor.shade_was_down 
    - delay: '00:00:02'    
    - service: switch.turn_off
      data_template:
        entity_id: >- 
         {%- if is_state("switch.somfy", "on")  -%}
          {{- "switch.somfy" -}}
          {%- else -%}
          {{- "switch.dummy" -}}
          {%- endif -%} 
    #- wait_template: "{{ states.binary_sensor.opening_patio_shade.state == 'off' }}"    
    - delay: '00:00:30'        
    - service: camera.snapshot
      data:
        entity_id: camera.master
        filename: '/config/www/Photos/master_{{ now().strftime("%Y%m%d-%H%M%S") }}.jpg'
    #- wait_template: "{{ states.binary_sensor.opening_patio_shade.state == 'off' }}"        
    - service: switch.turn_on
      data_template:
        entity_id: >- 
         {%- if is_state("binary_sensor.shade_was_down", "on")  -%}
          {{- "switch.somfy" -}}
          {%- else -%}
          {{- "switch.dummy" -}}
          {%- endif -%} 
    - service: counter.increment 
      entity_id: counter.motion_pics_den  
    - service: camera.snapshot
      data:
        entity_id: camera.livingroom_east
        filename: '/config/www/Photos/livingroom_east_{{ now().strftime("%Y%m%d-%H%M%S") }}.jpg'

camera:

#---Hurricane
  - platform: generic
    name: Atlantic Hurricane
    still_image_url: https://www.nhc.noaa.gov/xgtwo/two_atl_0d0.png?072333
    content_type: 'image/png'
#--- wyze cams    
  - platform: generic
    name: Den
    username: !secret camuser
    password: !secret campass
    authentication: basic
    still_image_url: !secret denstill
    stream_source: !secret denlive
    verify_ssl: false
    scan_interval: 5 
  - platform: generic
    name: Livingroom East
    username: !secret camuser
    password: !secret campass
    authentication: basic
    still_image_url: !secret lrestill
    stream_source: !secret lrelive
    verify_ssl: false
    scan_interval: 5   
  - platform: generic
    name: Livingroom North
    username: !secret camuser
    password: !secret campass
    authentication: basic
    still_image_url: !secret lrnstill
    stream_source: !secret lrnlive
    verify_ssl: false
    scan_interval: 5  
  - platform: generic
    name: Master
    username: !secret camuser
    password: !secret campass
    authentication: basic
    still_image_url: !secret masterstill
    stream_source: !secret masterlive
    verify_ssl: false
    scan_interval: 5    
  - platform: mqtt
    name: DenCamera Motion
    topic: myhome/cameraden/motion 


#-- Sensors

#{"uptime":" 15:08:34 up 3 days, 12 min, 0 users, load average: 2.33, 2.58, 2.65", "ssid":"SpiritOfTheRadio-g", "bitrate":"72.2 Mb/s", "signal_level":"100%", "link_quality":"85%", "noise_level":"0%" }
# topic : myhome/cameraden, messageId : , length : 220
#parse the message into the various fields  and place  into sensors.   Full message is also placed in a sensor

sensor:
  - platform: mqtt
    name: "camera_den_fullinfo"
    state_topic: "myhome/cameraden"
    value_template: "{{ value_json.uptime }}"

  - platform: mqtt
    name: "camera_den_uptime"
    state_topic: "myhome/cameraden"
    value_template: >
      {% if 'users' in states.sensor.camera_den_fullinfo.state.split(',')[1]  %}
      {{ states.sensor.camera_den_fullinfo.state.split(',')[0] | regex_replace(find='[0-9][0-9]:[0-9][0-9]:[0-9][0-9] up', replace='', ignorecase=False)}}
      {% else %}
      {{ states.sensor.camera_den_fullinfo.state.split(',')[0] | regex_replace(find='[0-9][0-9]:[0-9][0-9]:[0-9][0-9] up', replace='', ignorecase=False)~ states.sensor.camera_den_fullinfo.state.split(',')[1]}}
      {% endif %}

  - platform: mqtt
    name: "camera_den_users"
    state_topic: "myhome/cameraden"
    value_template: >
      {% if 'users' in states.sensor.camera_den_fullinfo.state.split(',')[1]  %}
      {{ states.sensor.camera_den_fullinfo.state.split(',')[1] | replace("users","",) }}
      {% else %}
      {{ states.sensor.camera_den_fullinfo.state.split(',')[2] | replace("users","",) }}
      {% endif %}

  - platform: mqtt
    name: "camera_den_load"
    state_topic: "myhome/cameraden"
    value_template:  >
      {% if 'load' in states.sensor.camera_den_fullinfo.state.split(',')[2]  %}
      {{ states.sensor.camera_den_fullinfo.state.split(',')[2] | replace("load average:","",) ~ states.sensor.camera_den_fullinfo.state.split(',')[3] ~ states.sensor.camera_den_fullinfo.state.split(',')[4] }}
      {% else %}
      {{ states.sensor.camera_den_fullinfo.state.split(',')[3] | replace("load average:","",) ~ states.sensor.camera_den_fullinfo.state.split(',')[4] ~ states.sensor.camera_den_fullinfo.state.split(',')[5]  }}
      {% endif %}

  - platform: mqtt
    name: "camera_den_ssid"
    state_topic: "myhome/cameraden"
    value_template: "{{ value_json.ssid }}"


  - platform: mqtt
    name: "camera_den_signal_level"
    state_topic: "myhome/cameraden"
    value_template: "{{ value_json.signal_level }}"

  - platform: mqtt
    name: "camera_den_link_quality"
    state_topic: "myhome/cameraden"
    value_template: "{{ value_json.link_quality}}"


  - platform: mqtt
    name: "camera_den_bitrate"
    state_topic: "myhome/cameraden"
    value_template: "{{ value_json.bitrate }}"


  - platform: mqtt
    name: "camera_den_noise_level"
    state_topic: "myhome/cameraden"
    value_template: "{{ value_json.noise_level }}"


